### ISSUE TITLE
Dynamic property changes

### ISSUE THREAD

**Issue by kpagratis** [smallrye/smallrye-config#1108]
Does smallrye-config have support for changing properties at runtime? 
Specifically when using k8s config maps, we'd like the ability to update the mount with new properties and have our app (quarkus) react.

Thanks

**Comment by kpagratis** [comment]
Thank you for the response. This is largely what I assumed but the advise against is not something I considered. 

In service of this goal I've done down the route of creating a `ConfigSource`
In simply trying to get something to show up for testing, I have the following which is causing a stackoverflow exception
```
public class MyConfigSource implements ConfigSource {

  @Override public int getOrdinal() {
    return 275;
  }

  @Override public Set<String> getPropertyNames() {
    return Set.of("my.prop");
  }

  @Override public String getValue(String propertyName) {
    return "some value";
  }

  @Override public String getName() {
    return "MyConfigSource";
  }
}
```

```
2024-02-06 09:11:21,136 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:5000)
        at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4470)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4969)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4914)
        at java.base/java.util.regex.Pattern$StartS.match(Pattern.java:3820)
        at java.base/java.util.regex.Matcher.search(Matcher.java:1738)
        at java.base/java.util.regex.Matcher.find(Matcher.java:758)
        at io.smallrye.config.common.utils.StringUtil.split(StringUtil.java:43)
        at io.smallrye.config.Converters$CollectionConverter.convert(Converters.java:737)
        at io.smallrye.config.Converters$CollectionConverter.convert(Converters.java:718)
        at io.smallrye.config.ProfileConfigSourceInterceptor.convertProfile(ProfileConfigSourceInterceptor.java:136)
        at io.smallrye.config.ConfigValue$1.compare(ConfigValue.java:313)
        at io.smallrye.config.ConfigValue$1.compare(ConfigValue.java:300)
        at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:34)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:25)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
        at io.smallrye.config.SmallRyeConfigBuilder$1.getProfiles(SmallRyeConfigBuilder.java:230)
        at io.smallrye.config.SmallRyeConfigBuilder$1.getProfiles(SmallRyeConfigBuilder.java:234)
        at io.smallrye.config.SmallRyeConfigBuilder$1.getProfiles(SmallRyeConfigBuilder.java:234)```

**Comment by radcortez** [comment]
Can you also provide me with the complete configuration? Thanks!

**Comment by kpagratis** [comment]
Are you asking for a reproducer?
I'm using `smallrye-config:3.5.2` 
I don't have the `my.prop` option in `application.properties` since my intention is to provide a value dynamically.

**Comment by radcortez** [comment]
Yes, the problem there is:

```java
 @Override public String getValue(String propertyName) {
    return "some value";
  }
```

There is a recursive call to keep looking for profiled properties parent, which stops once a value for the property is not found. In this case, you are always returning a property no matter which name is looked up for.

**Comment by kpagratis** [comment]
oh I see. Thanks!
