### ISSUE TITLE
SmallRyeConfig doesn't support "short" type config

### ISSUE THREAD

**Issue by jaikiran** [smallrye/smallrye-config#179]
The MicroProfile config spec[1] states:

> The following Converters are provided by MicroProfile Config by default:
> 
>     boolean and java.lang.Boolean , values for true (case insensitive) "true", "1", "YES", "Y" "ON". Any other value will be interpreted as false
> 
>     byte and java.lang.Byte
> 
>     short and java.lang.Short
> ....
> 

However, when trying out some unrelated thing in Quarkus, injecting a `short` config type ended up with:

```
Caused by: java.lang.IllegalArgumentException: No Converter registered for class short
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:215)
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:203)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:198)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:99)
	at io.quarkus.arc.runtime.ConfigBeanCreator.create(ConfigBeanCreator.java:48)
```
[1] https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc

**Comment by dmlloyd** [comment]
This was fixed.
