### ISSUE TITLE
Support array of objects in YAML property files

### ISSUE THREAD

**Issue by javahippie** [smallrye/smallrye-config#216]
## Description
I am using Smallrye Config via Quarkus 1.1.0.

Using arrays in application.yaml currently works fine for single values like this:

```yaml
de:
  javahippie:
    mpadmin:
      instances:
        - "https://bing.com"
        - "https://www.google.com"
```

I can access the property without any additional configuration as a list of strings. I was curious if it was possible to write my own converter for a list of objects, as I need more data in my application than just the urls, and tried this:

```yaml
de:
  javahippie:
    mpadmin:
      instances:
        -
          name: "Bing"
          uri: "https://bing.com"
        -
          name: "Google"
          uri: "https://www.google.com"
```

This is valid YAML and something that works in Spring Boot, when using a YAML as a property file. However, when I try to run Quarkus dev mode, it throws an exception:

```
11:30:37,337 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at io.smallrye.config.source.yaml.YamlConfigSource.escape(YamlConfigSource.java:146)
	at io.smallrye.config.source.yaml.YamlConfigSource.appendEscaped(YamlConfigSource.java:151)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:118)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)
	at io.smallrye.config.source.yaml.YamlConfigSource.populateFromEntryNode(YamlConfigSource.java:119)

11:30:37,343 INFO  [io.qua.dev.DevModeMain] Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
11:30:37,347 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.IllegalStateException: No configuration is available for this class loader
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:89)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:74)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:93)
	at io.quarkus.runtime.configuration.ConfigInstantiator.handleObject(ConfigInstantiator.java:45)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServerAfterFailedStart(VertxHttpRecorder.java:114)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup.handleFailedInitialStart(VertxHotReplacementSetup.java:30)
	at io.quarkus.dev.RuntimeUpdatesProcessor.startupFailed(RuntimeUpdatesProcessor.java:451)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:192)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:96)
```

Would it be possible to implement a feature like this with a MicroProfile Config source? If no custom converter is provided, this could be interpreted as a `List<Map<String, String>>` as default?

**Comment by dmlloyd** [comment]
It certainly isn't expected for it to fail in thin manner.  Since MP Config deals in strings, the value is meant to to be converted to a list of key-value pairs.  We don't have any map converters yet (just because there hasn't been a use case yet).

**Comment by radcortez** [comment]
This should fix the Stackoverflow issue:
https://github.com/smallrye/smallrye-config/pull/252

Regarding support for Arrays of Objects or Maps is another story. I recommend that we open a separate issue for that.

**Comment by javahippie** [comment]
Thank you very much!

**Comment by radcortez** [comment]
Actually, I'll leave this one open and create a new issue for the Stackoverflow problem.

**Comment by rolandjohann** [comment]
@dmlloyd how can we register custom converters at quarkus? I currently have an use case where I need to decode a collection of objects

**Comment by radcortez** [comment]
Hi @rolandjohann, you can register converters in Quarkus per the definition of MP Config. Please check here on how to do it:
https://quarkus.io/guides/config#custom-configuration-converters

**Comment by rolandjohann** [comment]
@radcortez thanks for the quick answer. Remembered that section previously. The converter turns out to be pretty useless as the string representation contains key value pairs but the delimiter is missing. When using different levels of nesting it gets more confusing. Is it possible to implement confiuration schemas like that posted by op?

```yaml
de:
  javahippie:
    mpadmin:
      instances:
        -
          name: "Bing"
          uri: "https://bing.com"
        -
          name: "Google"
          uri: "https://www.google.com"
```

**Comment by radcortez** [comment]
Yes, that is something that we need to figure out. I'll try to have a look on how we can implement this.

Also, we would love help if you want to contribute that piece :)

**Comment by rolandjohann** [comment]
Sure, but I need some guidance here as the internals of smallrye are pretty unknown to me

**Comment by radcortez** [comment]
Thanks! Try to have a look into the project and I'll help as much as I can.

Probably, you should start by looking into:
https://github.com/smallrye/smallrye-config/blob/58f66dadcf217b91d22d6393fe0cbd9f63984f83/sources/yaml/src/main/java/io/smallrye/config/source/yaml/YamlConfigSource.java

**Comment by dmlloyd** [comment]
> @radcortez thanks for the quick answer. Remembered that section previously. The converter turns out to be pretty useless as the string representation contains key value pairs but the delimiter is missing.

What do you mean by "missing"?

**Comment by fabmars** [comment]
He means that:
```
    admin:
      users:
        -
          email: "joe@gmail.com"
          username: "joe"
          password: "123456"
          roles:
            - "Moderator"
            - "Admin"
        -
          email: "jack@gmail.com"
          username: "jack"
          password: "654321"
          roles:
            - "Moderator"

```

When mapped to `List<String>`, gives  `[email=joe@gmail.comusername=joepassword=123456roles=Moderator\, Admin, email=jack@gmail.comusername=jackpassword=654321roles=Moderator]`
So, no separator between each value and the next key.

Worse, as you can see in my example, I used a nested list, and if we now map that config tree to List<User> with a custom converter, say, `UserConverter`, it it called 3 times (not two) with the following values.
- "email=joe@gmail.comusername=joepassword=123456roles=Moderator\"
- "Admin"
- "email=jack@gmail.comusername=jackpassword=654321roles=Moderator"

This wasn't unexpected though.
That was just for the sake of giving an example to @rolandjohann 's [statement](https://github.com/smallrye/smallrye-config/issues/216#issuecomment-604940814) and answer the question above.

**Comment by dmlloyd** [comment]
That is definitely a bug... the code is supposed to insert the right number of escapes based on the nesting level, but there must be a logic error that occurs when going from list to map.

**Comment by fabmars** [comment]
OK I'm definitely willing to take a look when I'm done with my current project...say within a week.

**Comment by radcortez** [comment]
Cool. Looking forward for your PR. Thanks! :)

**Comment by radcortez** [comment]
I have been looking into this and I think we should change a little bit on how we do things.

When we have a simple case, where the yaml end nodes can be translated 1 to 1 to property keys everything is ok. The issue is when we mix Maps and Lists that don't translate directly to a single unique key.

In the case, the value was going into a single key with several escapes that required the consumer to parse. Well, what if we just keep it in the original format which is easier to convert? :) Also we could add additional indexed keys that allow to retrieve values from lists.

Please have a look in here #335 and let me know any feedback. @fabmars @javahippie @rolandjohann
