### ISSUE TITLE
Exception when using with PowerMockito

### ISSUE THREAD

**Issue by deepak229** [smallrye/smallrye-config#381]
```
final Dispatcher dispatcher = MockDispatcherFactory.createDispatcher();
```
The above line of code when run a test with PowerMockRunner results in below exception.

```
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigProviderResolver: Provider io.smallrye.config.SmallRyeConfigProviderResolver not a subtype

	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:151)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.loadSpi(ConfigProviderResolver.java:146)
	at org.eclipse.microprofile.config.spi.ConfigProviderResolver.instance(ConfigProviderResolver.java:119)
	at org.eclipse.microprofile.config.ConfigProvider.<clinit>(ConfigProvider.java:74)
	at org.jboss.resteasy.microprofile.config.ResteasyConfigProvider.getConfig(ResteasyConfigProvider.java:11)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin$5.run(RegisterBuiltin.java:194)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin$5.run(RegisterBuiltin.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.isGZipEnabled(RegisterBuiltin.java:191)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.<clinit>(RegisterBuiltin.java:40)
	at org.jboss.resteasy.mock.MockDispatcherFactory.createDispatcher(MockDispatcherFactory.java:22)
```

**Comment by radcortez** [comment]
Hi @deepak229,

Are you interested in mocking the `ConfigProviderResolver` loaded by the `ServiceLoader`?

**Comment by radcortez** [comment]
No additional information provided, so closing the issue. Please feel free to reopen if you are still interested in this.
