### ISSUE TITLE
Injecting config property for Provider<List<String>> not working

### ISSUE THREAD

**Issue by norrman** [smallrye/smallrye-config#43]
Hi,

I'm experimenting with thorntail (2.2.0) and microprofile config (1.3.3). This works fine:

    @Inject
    @ConfigProperty(name="objectIds", defaultValue="")
    private List<String> objectIds;

However, I have a need to detect dynamically changing values from my custom source, so I tried this:
    
    @Inject
    @ConfigProperty(name="objectIds", defaultValue="")
    private Provider<List<String>> objectIds;

and that fails with:

    Caused by: java.lang.IllegalArgumentException: No Converter registered for class interface java.util.List
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:121)
	at io.smallrye.config.SmallRyeConfig.convert(SmallRyeConfig.java:101)

Using Provider works fine for Strings,

Cheers,
Per Norrman

**Comment by kenfinnigan** [comment]
Resolved with #44
