### ISSUE TITLE
Nested configmapping searches for properties inside of a map, instead of the standalone properties.

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-config#520]
I have a map inside a nested config mapping. Configuration properties adjacent to this map are being accessed as if they where part of the map. This causes them to not be found.

Exception:
```

__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-08 12:56:32,827 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-03-08 12:56:32,826 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00014: Property rabbitmq.conn.title.application-name is required but the value was not found or is empty
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:640)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:602)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:43)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:31)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:52)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy_0(ConfigBuildStep$registerConfigMappings510524965.zig:130)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy(ConfigBuildStep$registerConfigMappings510524965.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:543)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)


```

```
@ConfigMapping(prefix = "rabbitmq")
public interface RabbitMQConfiguration {
    ConnectionConfiguration conn();
}
```

Child configuration mapping:
```
public interface ConnectionConfiguration {
    Map<String, String> title();

    String applicationName();
}
```

My configuration:
```
rabbitmq.conn.title.somekey=somevalue
rabbitmq.conn.application-name=appname
```

Reproducer: 
[configmapping-optional.zip](https://github.com/smallrye/smallrye-config/files/6101187/configmapping-optional.zip)
mvn quarkus:dev to start, the exception is immediatly printed.

**Comment by radcortez** [comment]
Hi @Postremus. This was already fixed, and released in SR Config 1.11.1:
https://github.com/smallrye/smallrye-config/releases/tag/1.11.1
https://github.com/smallrye/smallrye-config/pull/510

And updated in Quarkus here:
https://github.com/quarkusio/quarkus/pull/15504

There are no breaking changes with latest Quarkus version, so you should be fine to manually update to SR Config 1.11.1 while you wait for the Quarkus release. Sorry for the inconvenience.

**Comment by Postremus** [comment]
Works perfectly, Thank you!

**Comment by radcortez** [comment]
Great!
