### ISSUE TITLE
Print causing exception of ConfigValidationException

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-config#521]
Follow up to https://github.com/quarkusio/quarkus/issues/15335

A small feature request for SR-Config. 
Could you also print the causing exception in case of a ConfigValidationException? Right now the thrown exception by the constructor can only be seen inside the debuger.

For example, the causing `URISyntaxException` is never shown.

```
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-03-08 07:42:05,142 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-03-08 07:42:05,141 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.lang.IllegalArgumentException: SRCFG00019: Failed to create new instance from Converter constructor
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:640)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:602)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:43)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:31)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:52)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy_0(ConfigBuildStep$registerConfigMappings510524965.zig:130)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigMappings510524965.deploy(ConfigBuildStep$registerConfigMappings510524965.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:543)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/1223135/110431761-80e3a700-80ae-11eb-8e26-d3ba98d3e662.png)

**Comment by radcortez** [comment]
Thanks for the suggestion. This is already fixed in #504. It requires a backport to the `1.x` branch.
