### ISSUE TITLE
Application fails to start in native image mode when some config sources are not available due to dead code elimination

### ISSUE THREAD

**Issue by mswiderski** [smallrye/smallrye-config#580]
When working with Quarkus application that is based on following extensions
- funqy Knative binding
- rest client
- rest client jackson

When application is compiled to native image it fails due to following error

````
May 23, 2021 8:56:56 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.jboss.resteasy.microprofile.config.ServletConfigSource not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:90)
	at io.smallrye.config.SmallRyeConfig.buildConfigSources(SmallRyeConfig.java:83)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:66)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:358)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1173)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:411)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
````

to root cause seems to be related to dead code elimination that removes `ServletConfigSource` from the class path as it is not referenced and thus leading to complete failure at startup.

Using Quarkus 1.13.2 which uses small rye config 1.11.1

**Comment by mswiderski** [comment]
a proposed fix is available as PR https://github.com/smallrye/smallrye-config/pull/581

essentially it allows to ignore failing instances without breaking the complete iterator.

**Comment by radcortez** [comment]
This is now fixed in https://github.com/quarkusio/quarkus/pull/17483.

**Comment by mswiderski** [comment]
Excellent, thanks a lot @radcortez
