### ISSUE TITLE
Smallrye config fail in Quarkus.1.13.6.FInal

### ISSUE THREAD

**Issue by hrstoyanov** [smallrye/smallrye-config#585]
@radcortez 

The YAML config parser in Quarkus.1.3.6.FInal seems messed up - not sure why ```client_cert_auth``` is considered boolean instead of enum, with default value false? 

Consider this code:
```
public enum ClientCertAuth {
    off, needed, required;
}

public interface EncryptionConfig {

    @NotBlank
    @WithName("level")
    @WithDefault("available_but_off")
    EncryptionLevel level();

    @WithName("trust_any_cert")
    @WithDefault("false")
    boolean trustAnyCertificate();

    @NotBlank
    @WithName("client_cert_auth")
    @WithDefault("off")
    ClientCertAuth clientCertAuth();

    @NotBlank
    @WithName("ssl_protocol")
    @WithDefault("TLS")
    String sslProtocol();

    interface KeystoreConfig {
        @NotBlank
        @WithName("location")
        String location();

        @NotBlank
        @WithName("format")
        @WithDefault("pkcs12")
        String format();

        @WithName("password")
        Optional<String> password();
    }

    @WithName("keystore")
    Optional<KeystoreConfig> keystore();

    @WithName("truststore")
    Optional<KeystoreConfig> truststore();

}
```

And this configuration data:
```
dbproxy:
  encryption:
    trust_any_cert: true
    client_cert_auth: off
    level: available_but_off
    ssl_protocol: TLS
    truststore:
       location: /temp/proxystore.jks
       format: 'jks'
       password: proxy123
    keystore:
       location: /temp/proxystore.jks
       format: jks
       password: proxy123
```

When Quarkus 1.13.6.FInal starts, I get this:
```
Powered by Quarkus 1.13.6.Final
12:46:48 INFO  [io.qu.de.de.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
12:46:48 ERROR [io.qu.ru.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.lang.IllegalArgumentException: SRCFG00039: The config property dbproxy.encryption.client_cert_auth with the config value "false" threw an Exception whilst being converted
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:808)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:767)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:46)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:34)
```

**Comment by hrstoyanov** [comment]
temporary  fix - comment out ```client_cert_auth``` in the YAML file.

**Comment by radcortez** [comment]
Hi @hrstoyanov,

The issue here is that `snakeyaml` automatically coverts any `off` value to `false` due to the spec rules of YAML 1.1: http://yaml.org/type/bool.html

Not much we can do here. If you can find a different name value instead of `off`, then it will be ok.

**Comment by hrstoyanov** [comment]
Super weird! Thanks for investigating, will pick a different name.
