### ISSUE TITLE
ParamConverter not resolved correctly for NestedMap with ConfigMapping

### ISSUE THREAD

**Issue by dirkbolte** [smallrye/smallrye-config#856]
Versions:
- Quarkus: `2.14.2.Final`
- Smallrye-config-core: `2.12.1`

I have the following line in `application.properties`: `test.1.text.prop=value`

I want to parse this into an object. My object looks like this:

```kotlin
@ConfigMapping(prefix = "test")
interface TestConfig {
    @get:WithParentName
    val prop: Map<Long, Map<String, TestClass>>

    interface TestClass {
        @get:WithName(value = "prop")
        val prop: String
    }
}
```

and a Service using this:

```kotlin
@Startup
@ApplicationScoped
class TestService(private val config: TestConfig)
```

I get the following exception when starting quarkus:

```
ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.NumberFormatException: SRCFG00030: Expected a long value, got "text"
	at io.smallrye.config.Converters.lambda$static$c244dc85$1(Converters.java:97)
	at io.smallrye.config.Converters$EmptyValueConverter.convert(Converters.java:980)
	at io.smallrye.config.Converters$TrimmingConverter.convert(Converters.java:1004)
	at io.smallrye.config.Converters$BuiltInConverter.convert(Converters.java:901)
	at io.smallrye.config.ConfigMappingProvider$GetOrCreateEnclosingGroupInMap$MapKey.key(ConfigMappingProvider.java:797)
	at io.smallrye.config.ConfigMappingProvider$GetOrCreateEnclosingGroupInMap.apply(ConfigMappingProvider.java:698)

```

The same code works when with `val prop: Map<String, Map<String, TestClass>>` as well as `val prop: Map<Long, Map<String, Map<String, String>>>` . From what I experience, I can provoke the error:

- nested mapping where map keys have different (primitive) type. 
- involves an object as final value of the map

**Comment by dirkbolte** [comment]
thx
