### ISSUE TITLE
Secret Keys Expressions doesn't support expansion on configuration values

### ISSUE THREAD

**Issue by michalvavrik** [smallrye/smallrye-config#921]
Secret Keys Expressions has same syntax as property expressions and they are only determined for secret keys expressions by knowledge of `handler` name. However I believe actual behavior needs to be better documented (or made compliant with config expressions) as I found the behavior surprising:

- `var=${handler:secret}postfix` is passed to the `handler#decode` as `secretpostfix` instead of `secret` and `var` value is result of `handler#decode`, while `postfix` is ignored; that comes down to this line https://github.com/smallrye/smallrye-config/blob/e22952bb3d3f8bbf0b0d1f379b7b611b18c4137b/implementation/src/main/java/io/smallrye/config/SecretKeysHandlerConfigSourceInterceptor.java#L24

**Comment by rsvoboda** [comment]
@radcortez can you please look into this? It can be quite confusing

**Comment by radcortez** [comment]
Yes,

A secret expression uses a double colon `::` to split the handler name of the secret value. So in this. case:

```properties
var1=${handler:secret}
var2=${var1}postfix
```

In `var1`, there is no secret handler definition. This is just a config expression, looking for config `handler` with a default to `secret`, so `var2` takes the value of `secretpostfix` (since `handler` is not available).

```properties
var1=${handler::secret}
var2=${var1}postfix
```

In this case, `var1` is a secret handler expression, so it queries a secret handler named `handler` and decodes the value `secret`. 

What we don't support yet, and is composed of expressions that mix a config expression and a secret handler. So, a lookup to `var1` will return you the decoded secret, but a lookup to `var2` will ignore the secret handler. I'm not totally sure if this is something we want to support. We need to discuss it.

**Comment by michalvavrik** [comment]
thanks @radcortez, the double colon thing makes sense, I made mistake when writing this issue and I removed it from the issue description now. 

However I don't think the behavior is predictable from documentation.

I can do this (no secret keys handler):

```
%profile1.ba=babovka
%profile1.bo=${profile1.ba}
```

and with `profile1` property `bo` is resolved to babovka, however this

```
%profile1.ha=${aes-gcm-nopadding::DGylA4FTy1pbtsvX0XYO_tgIwA3lCLzh-HZxfhEqPjfnHB6Nrw}
%profile1.secrets.profile1-app-prop-crypto-handler=${profile1.ha}
```

results in exception

```
3:03:32,609 INFO  [app] 13:03:30,788 Failed to start application (with profile [profile3, profile2, profile1, dev]): java.util.NoSuchElementException: SRCFG00011: Could not expand value profile1.ha in property secrets.profile1-app-prop-crypto-handler
13:03:32,612 INFO  [app] 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:80)
13:03:32,613 INFO  [app] 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:56)
13:03:32,615 INFO  [app] 	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
13:03:32,616 INFO  [app] 	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
13:03:32,617 INFO  [app] 	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
13:03:32,617 INFO  [app] 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:56)
13:03:32,618 INFO  [app] 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:35)
13:03:32,618 INFO  [app] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
13:03:32,618 INFO  [app] 	at io.smallrye.config.SecretKeysHandlerConfigSourceInterceptor.getValue(SecretKeysHandlerConfigSourceInterceptor.java:20)
13:03:32,619 INFO  [app] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
13:03:32,620 INFO  [app] 	at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
13:03:32,621 INFO  [app] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
13:03:32,621 INFO  [app] 	at io.smallrye.config.SecretKeysConfigSourceInterceptor.getValue(SecretKeysConfigSourceInterceptor.java:24)
13:03:32,622 INFO  [app] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
13:03:32,622 INFO  [app] 	at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
13:03:32,623 INFO  [app] 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
13:03:32,623 INFO  [app] 	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:323)
13:03:32,624 INFO  [app] 	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:230)
13:03:32,624 INFO  [app] 	at io.smallrye.config.ConfigMappingProvider.lambda$processLazyMapValue$0(ConfigMappingProvider.java:496)
13:03:32,625 INFO  [app] 	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:968)
13:03:32,625 INFO  [app] 	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:935)
13:03:32,626 INFO  [app] 	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
13:03:32,626 INFO  [app] 	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:935)
13:03:32,627 INFO  [app] 	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
13:03:32,627 INFO  [app] 	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:624)
13:03:32,627 INFO  [app] 	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
13:03:32,628 INFO  [app] 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
13:03:32,628 INFO  [app] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
13:03:32,628 INFO  [app] 	at io.quarkus.runtime.Application.start(Application.java:101)
13:03:32,629 INFO  [app] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
13:03:32,629 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
13:03:32,630 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
13:03:32,630 INFO  [app] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
13:03:32,631 INFO  [app] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
13:03:32,631 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:03:32,631 INFO  [app] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:03:32,631 INFO  [app] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:03:32,632 INFO  [app] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:03:32,632 INFO  [app] 	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
```

> What we don't support yet, and is composed of expressions that mix a config expression and a secret handler. So, a lookup to var1 will return you the decoded secret, but a lookup to var2 will ignore the secret handler. I'm not totally sure if this is something we want to support. We need to discuss it.

I'm not sure on right terminology, but if you call `var1=${handler::secret}postfix` call expression, then passing `secretpostix` to secret keys handler can't be expected behavior. If you meant something else, let's ignore this note, thanks.  If this is not supported, please document it.

**Comment by michalvavrik** [comment]
@radcortez I just tried it again, this time with double colon and I still can experience what I originally described:

```
ha=${aes-gcm-nopadding::DGylA4FTy1pbtsvX0XYO_tgIwA3lCLzh-HZxfhEqPjfnHB6Nrw}
secrets.profile1-app-prop-crypto-handler=${ha}
```

is resolved to `DGylA4FTy1pbtsvX0XYO_tgIwA3lCLzh-HZxfhEqPjfnHB6Nrw`

```
Expected: is "profile1"
  Actual: DGylA4FTy1pbtsvX0XYO_tgIwA3lCLzh-HZxfhEqPjfnHB6Nrw
```

**Comment by radcortez** [comment]
Yes, right now, it is not possible to mix secret handlers expressions with config expressions.

**Comment by michalvavrik** [comment]
Noted. Glad we understand each other now.
